# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mori-system.github.io
title: Morisystem
email: sc.choi@morisystem.com
author: CHOI AM
description: > # "Write an awesome description for your new site here.


copyright: 'Copyright &copy; 2018 Morisystem All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: web
    url: http://www.morisystem.com
  - title: github
    url: https://github.com/mori-system.com
  - title: linkedin
    url:
