url: https://mori-system.github.io
title: Morisystem
email: sc.choi@morisystem.com
author: CHOI AM
description: >

copyright: 'Copyright &copy; 2018 Morisystem All Rights Reserved.'
credits: 'Morisystem'


# Build settings
markdown: kramdown
permalink: pretty

social:
  - title: home
    url: https://mori-system.github.io/
  - title: facebook
    url: http://www.morisystem.com
  - title: twitter
    url: https://twitter.com/moriplanning
  - title: github
    url: https://github.com/mori-system
